export const companyData = {
  names: ["Vardaan", "Happy Nature", "Gopala"],
  products: {
    "Vardaan": [
      "Full Cream 6ltr",
      "Full Cream 500ml",
      "Full Cream 400ml",
      "Toned Milk 500ml",
      "Toned Milk 400ml",
      "DTM 500ml",
      "DTM 400ml",
      "DTM Bacha 170ml",
      "Family Pack 450 ml",
      "Cow Milk 500ml",
      "Cow Milk 350ml",
      "Buffalo Milk 1ltr",
      "Buffalo Milk 500ml",
      "Curd 400gm",
      "Curd 160grm",
      "Plain Chach 300ml",
      "Masala Chach 300ml",
      "Curd 5kg",
      "Curd 15kg",
    ],
    "Happy Nature": [
      "A1 Milk Gopala Top",
      "A2 Milk Gopala Top",
      "A1 Milk Pouch",
      "A2 Milk Pouch",
      "Slim Milk",
      "Buffalo Milk",
    ],
    "Gopala": ["Full Cream", "Toned Milk"],
  },
};
